// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-12-06
//     Description: EndPoints class for the table "DocumentoIdentidad"
// </auto-generated>
// -----------------------------------------------------------------------------

using Microsoft.AspNetCore.Http.HttpResults;
using Mozo.Api.Abstractions;
using Mozo.App.Maestro.DocumentoIdentidad;
using Mozo.Domain.Maestro;

namespace Mozo.Api.Maestro;
/// <summary>
/// Clase estatica que para llamar al grupo de end points "DocumentoIdentidad".
/// </summary>
public sealed partial class DocumentoIdentidadEndPoints : IEndpoint
{
    private const string CacheTag = "docidentidad";

    public string Prefix => "/maestro/documento-identidad";
    /// <summary>
    /// Función que devuelve el grupo de end points de la entidad "DocumentoIdentidad".
    /// </summary>
    public void MapEndpoint(RouteGroupBuilder g)
    {
        g.WithSecurity();

        g.MapGet("/active", SelAllActiveAsync)
          .WithResponses<IEnumerable<DocumentoIdentidadEntity>>(StatusCodes.Status200OK)
          .WithDescription("Obtener todos los Documentos de Identidad")
          .CacheOutput(CacheTag);
    }

}
public partial class DocumentoIdentidadEndPoints
{

    static async Task<IResult>
       SelAllActiveAsync(
        [AsParameters] DocumentoIdentidadFilter f,
        IDocumentoIdentidadService IDocumentoIdentidad
    )
    {   
        return Results.Ok(await IDocumentoIdentidad.SelAllActiveAsync(f));
    }

}

