// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-12-06
//     Description: EndPoints class for the table "Pais"
// </auto-generated>
// -----------------------------------------------------------------------------

using Microsoft.AspNetCore.Http.HttpResults;
using Mozo.Api.Abstractions;
using Mozo.App.Maestro.Pais;
using Mozo.App.Maestro.Pais.Contracts;
using Mozo.Domain.Maestro;

namespace Mozo.Api.Maestro;
/// <summary>
/// Clase estatica que para llamar al grupo de end points "Pais".
/// </summary>
public sealed partial class PaisEndPoints : IEndpoint
{
    private const string CacheTag = "pais";

    public string Prefix => "/maestro/pais";
    /// <summary>
    /// Función que devuelve el grupo de end points de la entidad "Pais".
    /// </summary>
    public void MapEndpoint(RouteGroupBuilder g)
    {
        g.WithSecurity();  

        g.MapGet("/active", SelAllActiveAsync)
          .WithResponses<IEnumerable<PaisOption>>(StatusCodes.Status200OK)
          .WithDescription("Obtener todos los Paises")
          .CacheOutput(CacheTag);
    }

}
public partial class PaisEndPoints
{
    static async Task<IResult>
        SelAllActiveAsync(IPaisService IPais)
    {      
        IEnumerable<PaisOption> r = await IPais.SelAllActiveAsync();
        return Results.Ok(r);
    }

}

