// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-10-06
//     Description: EndPoints class for the table "trftipoparticular"
// </auto-generated>
// -----------------------------------------------------------------------------

#nullable enable
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.OutputCaching;
using Mozo.Api.Abstractions;
using Mozo.App.Maestro.TipoParticular;
using Mozo.Domain.Maestro;
using Mozo.Shared.Models;

namespace Mozo.Api.Maestro;
/// <summary>
/// Clase estatica que para llamar al grupo de end points "trftipoparticular".
/// </summary>
public sealed partial class TipoParticularEndPoints : IEndpoint
{

    private const string CacheTag = "tipoparticular";

    public string Prefix => "/maestro/tipo-particular";

    /// <summary>
    /// Función que devuelve el grupo de end points de la entidad "trftipoparticular".
    /// </summary>
    public void MapEndpoint(RouteGroupBuilder g)
    {
        g.WithSecurity();

        g.MapPost("/", InsertAsync)
          .WithResponsesValue<int>(StatusCodes.Status200OK)
          .WithDescription("Insertar una Tipo");

        g.MapPut("/", UpdateByIdAsync)
            .WithResponsesValue<int>(StatusCodes.Status200OK)
            .Produces(StatusCodes.Status404NotFound)
            .WithDescription("Actualizar una Tipo");

        g.MapPatch("/state", UpdateStateByIdAsync)
            .WithResponsesValue<int>(StatusCodes.Status200OK)
            .Produces(StatusCodes.Status404NotFound)
            .WithDescription("Activar o desactivar un Tipo");

        g.MapPatch("/default", UpdateDefaultAsync)
            .WithResponsesValue<int>(StatusCodes.Status200OK)
            .Produces(StatusCodes.Status404NotFound)
            .WithDescription("Actualizar Default");

        g.MapDelete("/", DeleteByIdAsync)
             .WithResponsesValue<int>(StatusCodes.Status200OK)
             .Produces(StatusCodes.Status404NotFound)
             .WithDescription("Eliminar una Tipo");

        g.MapGet("/", SelByIdAsync)
            .WithResponses<TipoParticularEntity>(StatusCodes.Status200OK)
            .Produces(StatusCodes.Status404NotFound)
            .WithDescription("Obtener un Tipo");

        g.MapGet("/all", SelAllAsync)
            .WithResponses<PagedResult<TipoParticularListItem>>(StatusCodes.Status200OK)
            .WithDescription("Obtener todas los Tipos");

        g.MapGet("/children", SelAllChildrenAsync)
           .WithResponses<PagedResult<TipoParticularListItem>>(StatusCodes.Status200OK)
           .WithDescription("Obtener todas los hijos de los Tipos")
           .CacheOutput(CacheTag);
  
        g.MapGet("/father-children/active", SelAllActiveFatherAndChildrenAsync)
            .WithResponses<IEnumerable<TipoParticularEntity>>(StatusCodes.Status200OK)
            .WithDescription("Obtener todas los padres e hijos activos")
            .CacheOutput(CacheTag);

        g.MapGet("/modules/groups", SelAllActiveGroupsByModuleAsync)
           .WithResponses<IEnumerable<TipoParticularEntity>>(StatusCodes.Status200OK)
            .WithDescription("Obtener todas los grupos por modulos")
            .CacheOutput(CacheTag);

        g.MapGet("/next-order", SelOrderNextAsync)
            .WithResponsesValue<int>(StatusCodes.Status200OK)
            .Produces(StatusCodes.Status404NotFound)
            .WithDescription("Obtener el siguiente numero de orden del grupo");

        g.MapGet("/group", SelByIdGroupAsync)
            .WithResponses<TipoParticularEntity>(StatusCodes.Status200OK)
            .Produces(StatusCodes.Status404NotFound)
            .WithDescription("Obtener un grupo por id");
    }

}
public partial class TipoParticularEndPoints
{
    private static Task InvalidateCacheAsync(IOutputCacheStore cacheStore)
        => cacheStore.InvalidateCacheAsync(CacheTag);

    private static async Task<IResult>
    InsertAsync(       
       TipoParticularEntity m,
       IOutputCacheStore cacheStore,
       ITipoParticularService ITipo
       )
    {
        m.CoTipoParticular = await ITipo.InsertAsync(m);
        await InvalidateCacheAsync(cacheStore);
        return Results.Created($"/{m.CoTipoParticular}", m.CoTipoParticular);
    }

    private static async Task<IResult>
        UpdateByIdAsync(
         TipoParticularEntity m,
         IOutputCacheStore cacheStore,
         ITipoParticularService ITipo
    )
    {
        int filas = await ITipo.UpdateByIdAsync(m);
        if (filas == 0) return Results.NotFound();

        await InvalidateCacheAsync(cacheStore);
        return Results.Ok(filas);
    }



    private static async Task<IResult>
     UpdateStateByIdAsync(
        TipoParticularEntity m,
        IOutputCacheStore cacheStore,
        ITipoParticularService ITipo
     )
    {
        int filas = await ITipo.UpdateStateByIdAsync(m);
        if (filas == 0) return Results.NotFound();

        await InvalidateCacheAsync(cacheStore);
        return Results.Ok(filas);
    }

    private static async Task<IResult>
    UpdateDefaultAsync(
      TipoParticularEntity m,
      IOutputCacheStore cacheStore,
      ITipoParticularService ITipo
    )
    {
        int filas = await ITipo.UpdateDefaultAsync(m);
        if (filas == 0) return Results.NotFound();

        await InvalidateCacheAsync(cacheStore);
        return Results.Ok(filas);
    }

    private static async Task<IResult>
        DeleteByIdAsync(
           [AsParameters] TipoParticularFilter f,
           IOutputCacheStore cacheStore,
           ITipoParticularService ITipo
    )
    {
        int filas = await ITipo.DeleteByIdAsync(f);
        if (filas == 0) return Results.NotFound();

        await InvalidateCacheAsync(cacheStore);
        return Results.Ok(filas);
    }

  

    private static async Task<IResult> 
        SelAllActiveGroupsByModuleAsync(
        [AsParameters] TipoParticularFilter f, 
        ITipoParticularService ITipo
    )
    {       
        return Results.Ok(await ITipo.SelAllActiveGroupsByModuleAsync(f));
    }



    private static async Task<IResult>
    SelAllAsync(
        [AsParameters] TipoParticularFilter f,
        ITipoParticularService ITipo
    )
    {
        if (f.FlEstReg == 1)
            return Results.Ok(await ITipo.SelAllActiveAsync(f));
        else
            return Results.Ok(await ITipo.SelAllAsync(f));
    }

    private static async Task<IResult>
     SelAllChildrenAsync(
        [AsParameters] TipoParticularFilter f,
        ITipoParticularService ITipo
     )
    {
        if (f.FlEstReg == 1)
            return Results.Ok(await ITipo.SelAllActiveChildrenAsync(f));        
        else
            return Results.Ok(await ITipo.SelAllChildrenAsync(f));
    }



    private static async Task<IResult>
    SelAllActiveFatherAndChildrenAsync(
        [AsParameters] TipoParticularFilter f,
        ITipoParticularService ITipo
    )
    {       
        IEnumerable<TipoParticularEntity> r = await ITipo.SelAllActiveFatherAndChildrenAsync(f);
        return Results.Ok(r);
    }

    private static async Task<IResult> 
    SelByIdAsync(
        [AsParameters] TipoParticularFilter f,
        ITipoParticularService ITipo
    )
    {        
        TipoParticularEntity? i = await ITipo.SelByIdAsync(f);
        if (i == null)
            return Results.NotFound();
        return Results.Ok(i);
    }

    private static async Task<IResult> 
        SelOrderNextAsync(
        [AsParameters] TipoParticularFilter f, 
        ITipoParticularService ITipo
    )
    {       
        return Results.Ok(await ITipo.SelOrderNextAsync(f));
    }

    private static async Task<IResult> 
        SelByIdGroupAsync(
            [AsParameters] TipoParticularFilter f, 
            ITipoParticularService ITipo
    )
    {
        TipoParticularEntity? i = await ITipo.SelByIdGroupAsync(f);
        if (i == null)
            return Results.NotFound();
        return Results.Ok(i);
    }

}

