// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-12-06
//     Description: EndPoints class for the table "trftipogeneral"
// </auto-generated>
// -----------------------------------------------------------------------------

#nullable enable

using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.OutputCaching;
using Mozo.Api.Abstractions;
using Mozo.App.Maestro.TipoGeneral;
using Mozo.App.Maestro.TipoGeneral.Contracts;
using Mozo.Domain.Maestro;

namespace Mozo.Api.Maestro;
///<summary>
/// Endpoints para gestión de TipoGeneral
///</summary>
///<history>
/// Create by Jonatan Abregu
///</history>
public sealed partial class TipoGeneralEndPoints : IEndpoint
{
    private const string CacheTag = "tipogeneral";

    public string Prefix => "/maestro/tipo-general";


    /// <summary>
    /// Mapea todas las rutas de TipoGeneral
    /// </summary>
    public void MapEndpoint(RouteGroupBuilder g)
    {
        g.WithSecurity();

        g.MapGet("/", SelByIdAsync)
          .WithResponses<TipoGeneralEditResponse>(StatusCodes.Status200OK)
         .Produces(StatusCodes.Status404NotFound)
         .WithDescription("Obtener una Tipo General")
       ;

        g.MapGet("/active", SelAllActiveAsync)
          .WithResponses<IEnumerable<TipoGeneralOption>>(StatusCodes.Status200OK)
          .Produces(StatusCodes.Status404NotFound)
          .WithDescription("Obtener todos los Tipo General activos")
          .CacheOutput(CacheTag);

        g.MapGet("/modulos/active", SelAllActiveByModuleAsync)
          .WithResponses<IEnumerable<TipoGeneralOption>>(StatusCodes.Status200OK)
          .Produces(StatusCodes.Status404NotFound)
          .WithDescription("Obtener todos los Tipo General activos del Módulo")
         .CacheOutput(CacheTag);
    }

}
public partial class TipoGeneralEndPoints
{

    private static async Task<IResult>
        SelByIdAsync(
        [AsParameters]  TipoGeneralFilter f,
        ITipoGeneralService ITipoGeneral)
    {
        TipoGeneralEditResponse? i = await ITipoGeneral.SelByIdAsync(f);
        if (i == null)
            return Results.NotFound();
        return Results.Ok(i);
    }
    private static async Task<IResult> 
        SelAllActiveAsync(
       [AsParameters] TipoGeneralFilter f,
        ITipoGeneralService ITipoGeneral
        )
    {     
        IEnumerable<TipoGeneralOption> r = await ITipoGeneral.SelAllActiveAsync(f);
        return Results.Ok(r.OrderBy(x => x.NuOrden));
    }

    private static async Task<IResult>
        SelAllActiveByModuleAsync(
            [AsParameters] TipoGeneralFilter f,
            ITipoGeneralService ITipoGeneral)
    {       
        IEnumerable<TipoGeneralOption> r = await ITipoGeneral.SelAllActiveByModuleAsync(f);
        return Results.Ok(r.OrderBy(x => x.NuOrden));
    }

}

