// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-10-01
//     Description: Model class for the table "trfmotivonotacredito"
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace Mozo.Domain.Contabilidad;




/// <summary>
/// Entidad que representa la tabla "trfmotivonotacredito".
/// </summary>
public class MotivoNotaCreditoEntity : BaseEntity
{
  public int CoMotivoNotaCredito { get; set; }
  public int CoPais { get; set; }
  public string NoCodigo { get; set; }
  public string NoMotivoNotaCredito { get; set; }
}
