// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-10-02
//     Description: EndPoints class for the table "tblatributo"
// </auto-generated>
// -----------------------------------------------------------------------------

#nullable enable

using Microsoft.AspNetCore.Http.HttpResults;
using Mozo.Api.Abstractions;
using Mozo.App.Catalogo.Atributo;
using Mozo.Domain.Catalogo;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Mozo.Api.Catalogo;
/// <summary>
/// Clase estatica que para llamar al grupo de end points "tblatributo".
/// </summary>
public sealed partial class AtributoEndPoints : IEndpoint
{
    public string Prefix => "/catalogo/atributo";

    /// <summary>
    /// Función que devuelve el grupo de end points de la entidad "tblatributo".
    /// </summary>
    public void MapEndpoint(RouteGroupBuilder g)
    {
        g.DisableAntiforgery().RequireAuthorization();
        g.MapPost("/", InsertAsync);
        g.MapPut("/", UpdateByIdAsync);
        g.MapPatch("/state", UpdateStateByIdAsync);
        g.MapDelete("/", DeleteByIdAsync);
        g.MapGet("/all", SelAllAsync);
        g.MapGet("/active", SelAllActiveAsync);
        g.MapGet("/", SelByIdAsync);
    }
}
/// <summary>
/// Clase estatica donde se encuentran los procedimientos y funciones de los end points "tblatributo".
/// </summary>
public partial class AtributoEndPoints
{

    static async Task<IResult>
        InsertAsync(AtributoEntity m, IAtributoService IAtributo)
    {       
        m.CoAtributo = await IAtributo.InsertAsync(m);
        return  Results.Created($"/{m.CoAtributo}", m.CoAtributo);
    }

    static async Task<IResult>
        UpdateByIdAsync(AtributoEntity m, IAtributoService IAtributo)
    {
        int filas = await IAtributo.UpdateByIdAsync(m);
        return filas > 0 ? Results.Ok(filas) : Results.NotFound();
    }

    static async Task<IResult>
        UpdateStateByIdAsync(AtributoEntity m, IAtributoService IAtributo)
    {
        int filas = await IAtributo.UpdateStateByIdAsync(m);
        return filas > 0 ? Results.Ok(filas) : Results.NotFound();
    }

    static async Task<IResult>
        DeleteByIdAsync(
        [AsParameters] AtributoFilter f,
         IAtributoService IAtributo)
    {
        int filas = await IAtributo.DeleteByIdAsync(f);
        return filas > 0 ? Results.Ok(filas) : Results.NotFound();
    }

    static async Task<IResult>
        SelAllAsync([AsParameters] AtributoFilter f,
        IAtributoService IAtributo)
    {   
        return  Results.Ok(await IAtributo.SelAllAsync(f));
    }

    static async Task<IResult>
        SelAllActiveAsync(
        [AsParameters] AtributoFilter f,
        IAtributoService IAtributo)
    {   
        return  Results.Ok(await IAtributo.SelAllActiveAsync(f));
    }

    static async Task<IResult>
        SelByIdAsync(
        [AsParameters] AtributoFilter f,
        IAtributoService IAtributo)
    {        
        AtributoEntity? i = await IAtributo.SelByIdAsync(f);
        if (i == null)
            return  Results.NotFound();
        return  Results.Ok(i);
    }

}
