// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-10-06
//     Description: EndPoints class for the table "tblproductoprecio"
// </auto-generated>
// -----------------------------------------------------------------------------

#nullable enable

using Microsoft.AspNetCore.Http.HttpResults;

using Mozo.Api.Abstractions;
using Mozo.App.Catalogo.ProductoPrecio;
using Mozo.Domain.Catalogo;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Mozo.Api.Catalogo;
/// <summary>
/// Clase estatica que para llamar al grupo de end points "tblproductoprecio".
/// </summary>
public sealed partial class ProductoPrecioEndPoints : IEndpoint
{
    public string Prefix => "/catalogo/producto-precio";

/// <summary>
/// Función que devuelve el grupo de end points de la entidad "tblproductoprecio".
/// </summary>
	public void MapEndpoint(RouteGroupBuilder g)
	{
		g.DisableAntiforgery().RequireAuthorization();
		g.MapPost("/", InsertAsync);
		g.MapPut("/", UpdateByIdAsync);
		g.MapPatch("/state", UpdateStateByIdAsync);
		g.MapDelete("/", DeleteByIdAsync);
		g.MapGet("/all", SelAllAsync);
		g.MapGet("/active", SelAllActiveAsync);
		g.MapGet("/", SelByIdAsync);
	}
}
/// <summary>
/// Clase estatica donde se encuentran los procedimientos y funciones de los end points "tblproductoprecio".
/// </summary>
public partial class ProductoPrecioEndPoints
{

	static async Task<IResult> InsertAsync(ProductoPrecioEntity m, IProductoPrecioService IProductoprecio)
	{
		
		m.CoProductoPrecio = await IProductoprecio.InsertAsync(m);
		return  Results.Created($"/{m.CoProductoPrecio}", m.CoProductoPrecio);
	}

	static async Task<IResult> UpdateByIdAsync(ProductoPrecioEntity m, IProductoPrecioService IProductoprecio)
	{
		int filas = await IProductoprecio.UpdateByIdAsync(m);
		return filas > 0 ? Results.Ok(filas) : Results.NotFound();
	}

	static async Task<IResult>
	UpdateStateByIdAsync(
			ProductoPrecioEntity m,
			IProductoPrecioService IProductoprecio)
	{
		int filas = await IProductoprecio.UpdateStateByIdAsync(m);
		return filas > 0 ? Results.Ok(filas) : Results.NotFound();
	}

	static async Task<IResult> DeleteByIdAsync(
	[AsParameters] ProductoPrecioFilter f,
		IProductoPrecioService IProductoprecio)
	{
		int filas = await IProductoprecio.DeleteByIdAsync(f);
		return filas > 0 ? Results.Ok(filas) : Results.NotFound();
	}

	static async Task<IResult> 
	SelAllAsync(
		[AsParameters] ProductoPrecioFilter f,
		IProductoPrecioService IProductoprecio
	)
	{
	
		IEnumerable<ProductoPrecioEntity> r = await IProductoprecio.SelAllAsync(f);
		return  Results.Ok(r);
	}

	static async Task<IResult> SelAllActiveAsync(
		[AsParameters] ProductoPrecioFilter f,
		IProductoPrecioService IProductoprecio
	)
	{
		
		IEnumerable<ProductoPrecioEntity> r = await IProductoprecio.SelAllActiveAsync(f);
		return  Results.Ok(r);
	}

	static async Task<IResult> SelByIdAsync([AsParameters] ProductoPrecioFilter f, IProductoPrecioService IProductoprecio)
	{		
		ProductoPrecioEntity? i = await IProductoprecio.SelByIdAsync(f);
		if (i == null)
			return  Results.NotFound();
		return  Results.Ok(i);
	}

}
