// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-10-06
//     Description: EndPoints class for the table "trftipoparticular"
// </auto-generated>
// -----------------------------------------------------------------------------
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.OutputCaching;

using Mozo.ApiSeguridad.Helper;
using Mozo.CatalogoBusiness;
using Mozo.MaestroBusiness;
using Mozo.Model;
using Mozo.Model.Catalogo;
using Mozo.Model.Maestro;
using Mozo.Model.Seguridad;

namespace Mozo.Api.Maestro;
/// <summary>
/// Clase estatica que para llamar al grupo de end points "trftipoparticular".
/// </summary>
public static partial class TipoParticularEndPoints
{

    private const string CacheTag = "tipoparticular";

    /// <summary>
    /// Función que devuelve el grupo de end points de la entidad "trftipoparticular".
    /// </summary>
    public static RouteGroupBuilder MapTipoParticular(this RouteGroupBuilder g)
    {
        g.WithSecurity();

        g.MapPost("/", InsertAsync)
          .WithResponsesValue<int>(StatusCodes.Status200OK)
          .WithDescription("Insertar una Tipo");

        g.MapPut("/", UpdateAsync)
            .WithResponsesValue<int>(StatusCodes.Status200OK)
            .WithDescription("Actualizar una Tipo");

        g.MapPatch("/state", UpdateStateAsync)
            .WithResponsesValue<int>(StatusCodes.Status200OK)
            .WithDescription("Activar o desactivar un Tipo");

        g.MapPatch("/command", UpdateCommandAsync)
           .WithResponsesValue<int>(StatusCodes.Status200OK)
           .WithDescription("Actualizar comando");

        g.MapPatch("/default", UpdateDefaultAsync)
            .WithResponsesValue<int>(StatusCodes.Status200OK)
            .WithDescription("Actualizar Default");

        g.MapDelete("/", DeleteByIdAsync)
             .WithResponses(StatusCodes.Status204NoContent)
             .WithDescription("Eliminar una Tipo");

        g.MapGet("/", SelByIdAsync)
            .WithResponses<TipoParticularModel>(StatusCodes.Status200OK)
            .Produces(StatusCodes.Status404NotFound)
            .WithDescription("Obtener un Tipo");

        g.MapGet("/all", SelAllAsync)
            .WithResponses<IEnumerable<TipoParticularModel>>(StatusCodes.Status200OK)
            .WithDescription("Obtener todas los Tipos");

        g.MapGet("/children", SelAllChildrenAsync)
           .WithResponses<IEnumerable<TipoParticularModel>>(StatusCodes.Status200OK)
           .WithDescription("Obtener todas los hijos de los Tipos")
           .CacheOutput(CacheTag);
  
        g.MapGet("/father-children/active", SelAllActiveFatherAndChildrenAsync)
            .WithResponses<IEnumerable<TipoParticularModel>>(StatusCodes.Status200OK)
            .WithDescription("Obtener todas los padres e hijos activos")
            .CacheOutput(CacheTag);

        g.MapGet("/modules/groups", SelAllActiveGroupsByModuleAsync)
           .WithResponses<IEnumerable<TipoParticularModel>>(StatusCodes.Status200OK)
            .WithDescription("Obtener todas los grupos por modulos")
            .CacheOutput(CacheTag);

        g.MapGet("/next-order", SelOrderNextAsync)
            .WithResponsesValue<int>(StatusCodes.Status200OK)
            .Produces(StatusCodes.Status404NotFound)
            .WithDescription("Obtener el siguiente numero de orden del grupo");

        g.MapGet("/group", SelByIdGroupAsync)
            .WithResponses<TipoParticularModel>(StatusCodes.Status200OK)
            .Produces(StatusCodes.Status404NotFound)
            .WithDescription("Obtener un grupo por id");

        return g;
    }

}
public static partial class TipoParticularEndPoints
{
    private static Task InvalidateCacheAsync(IOutputCacheStore cacheStore)
        => cacheStore.InvalidateCacheAsync(CacheTag);

    private static async Task<IResult>
      InsertAsync(       
       TipoParticularModel m,
       IOutputCacheStore cacheStore,
       ITipoParticularBusiness ITipo
       )
    {
        m.CoTipo = await ITipo.InsertAsync(m);
        await InvalidateCacheAsync(cacheStore);
        return Results.Created($"/{m.CoTipo}", m.CoTipo);
    }

    private static async Task<IResult>
        UpdateAsync(
         TipoParticularModel m,
         IOutputCacheStore cacheStore, 
         ITipoParticularBusiness ITipo
    )
    {        
        await ITipo.UpdateAsync(m);
        await InvalidateCacheAsync(cacheStore);
        return Results.Ok(m.CoTipo);
    }

    private static async Task<IResult>
        UpdateCommandAsync(
            TipoParticularModel m, 
            IOutputCacheStore cacheStore,  
            ITipoParticularBusiness ITipo
    )
    {
        
        await ITipo.UpdateCommandAsync(m);
        await InvalidateCacheAsync(cacheStore);
        return Results.Ok(m.CoTipo);
    }

    private static async Task<IResult>
     UpdateStateAsync(
        TipoParticularModel m, 
        IOutputCacheStore cacheStore, 
        ITipoParticularBusiness ITipo
     )
    {

        await ITipo.UpdateStateAsync(m);
        await InvalidateCacheAsync(cacheStore);
        return Results.Ok(m.CoTipo);
    }

    private static async Task<IResult>
    UpdateDefaultAsync(
      TipoParticularModel m,
      IOutputCacheStore cacheStore,
      ITipoParticularBusiness ITipo
    )
    {
        await ITipo.UpdateDefaultAsync(m);
        await InvalidateCacheAsync(cacheStore);
        return Results.Ok(m.CoTipo);
    }

    private static async Task<IResult>
        DeleteByIdAsync(
           [AsParameters] TipoParticularFilterDto f,
           IOutputCacheStore cacheStore, 
           ITipoParticularBusiness ITipo
    )
    {   
        await ITipo.DeleteByIdAsync(f);
        await InvalidateCacheAsync(cacheStore);
        return Results.NoContent();
    }

  

    private static async Task<IResult> 
        SelAllActiveGroupsByModuleAsync(
        [AsParameters] TipoParticularFilterDto f, 
        ITipoParticularBusiness ITipo
    )
    {       
        return Results.Ok(await ITipo.SelAllActiveGroupsByModuleAsync(f));
    }



    private static async Task<IResult>
        SelAllAsync(
        [AsParameters] TipoParticularFilterDto f,
        ITipoParticularBusiness ITipo
    )
    {
        if (f.FlEstReg == 1)
            return Results.Ok(await ITipo.SelAllActiveAsync(f));
        else
            return Results.Ok(await ITipo.SelAllAsync(f));
    }

    private static async Task<IResult>
     SelAllChildrenAsync(
        [AsParameters] TipoParticularFilterDto f,
        ITipoParticularBusiness ITipo
     )
    {
        if (f.FlEstReg == 1)
            return Results.Ok(await ITipo.SelAllActiveChildrenAsync(f));        
        else
            return Results.Ok(await ITipo.SelAllChildrenAsync(f));
    }



    private static async Task<IResult>
    SelAllActiveFatherAndChildrenAsync(
        [AsParameters] TipoParticularFilterDto f,
        ITipoParticularBusiness ITipo
    )
    {       
        IEnumerable<TipoParticularModel> r = await ITipo.SelAllActiveFatherAndChildrenAsync(f);
        return Results.Ok(r);
    }

    private static async Task<IResult> 
    SelByIdAsync(
        [AsParameters] TipoParticularFilterDto f,
        ITipoParticularBusiness ITipo
    )
    {        
        TipoParticularModel? i = await ITipo.SelByIdAsync(f);
        if (i == null)
            return Results.NotFound();
        return Results.Ok(i);
    }

    private static async Task<IResult> 
        SelOrderNextAsync(
        [AsParameters] TipoParticularFilterDto f, 
        ITipoParticularBusiness ITipo
    )
    {       
        return Results.Ok(await ITipo.SelOrderNextAsync(f));
    }

    private static async Task<IResult> 
        SelByIdGroupAsync(
            [AsParameters] TipoParticularFilterDto f, 
            ITipoParticularBusiness ITipo
    )
    {
        TipoParticularModel? i = await ITipo.SelByIdGroupAsync(f);
        if (i == null)
            return Results.NotFound();
        return Results.Ok(i);
    }

}

